"""empty message

Revision ID: 2f5c92724975
Revises: ed877cf7f3a2
Create Date: 2022-03-16 00:31:43.894468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5c92724975'
down_revision = 'ed877cf7f3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor1')
    # ### end Alembic commands ###
