"""empty message

Revision ID: d4fd3fa1b9af
Revises: 2f5c92724975
Create Date: 2022-03-16 00:32:21.916000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fd3fa1b9af'
down_revision = '2f5c92724975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor2')
    # ### end Alembic commands ###
